### ISSUE TITLE
Write an os in rust is 404

### ISSUE THREAD

**Issue by CrispyBacon1999** [tuvtran/project-based-learning#166]
## Expected Behavior

Actual webpage is loaded when [Write an OS in pure Rust](https://os.phil-opp.com/news/2018-03-09-pure-rust/) is clicked

## Current Behavior

Webpage loads as a page not found

## Steps to Reproduce

Click link from readme

**Comment by Dude9303** [comment]
The link takes you to an old article on the blog. 'https://os.phil-opp.com/news/2018-03-09-pure-rust/.'
Needs to be updated to its base url. 'https://os.phil-opp.com/'
