### ISSUE TITLE
Update the tutorial for "Building a container from scratch in Go - Liz Rice (Microscaling Systems)"

### ISSUE THREAD

**Issue by mayankshah1607** [tuvtran/project-based-learning#172]
### Description
The instructor in the above mentioned video has created a new version of the same tutorial, which can be found [here](https://www.youtube.com/watch?v=8fi7uSYlOdc)

### Why
It is always good to keep resources and tutorials up-to-date. The new video talks about namespaces, chroot and cgroups, and speaks about containers at a greater depth.

### Is this something you're interested in working on?
Yes.

**Comment by akshaydeep06** [comment]
I would like to make this change if no one is working on it .

**Comment by loveyue123** [comment]
i don't know

**Comment by tuvtran** [comment]
Fixed
