### ISSUE TITLE
Dead link: Building Blockchain in Go

### ISSUE THREAD

**Issue by havspect** [tuvtran/project-based-learning#265]
The link for the series 'Building Blockchain in Go' is dead. Yet, the blog is still online under a new domain.

## Expected Behavior

Change link!

## Possible Solution

New link: https://jeiwan.net/posts/building-blockchain-in-go-part-1/

**Comment by havspect** [comment]
Duplicate

**Comment by soberlinn** [comment]
CO -triple Mean

control/.com/contact 
—————
(命題充要條件： S is just S；H is always be H)

L-從屬接點
LIN SHU PO
Lam Syu Baak
主格型態：soberlinn 
Tranferspot:
A(m)bout PC (protect-cycle-circle)
Anbo-fb(family base)-
Inside suggestion:Quah
Explain and firewall:
（外接式F-base-可聯繫家用之SCSI
Aber,並非實際應用；
Referring note:
請參考SCSI-3之最高上限做分層管制/上限後為分形處理層-請告知MZ🦎)

Output-自訂（Am）
( input-Quan)
