### ISSUE TITLE
NestJS speedrun walkthrough plz

### ISSUE THREAD

**Issue by s3xysteak** [tuvtran/project-based-learning#504]
### Description

Need a NestJS speedrun walkthrough plz 🙏 

### Why

NestJS is very popular now.

### Possible Implementation & Open Questions

Maybe need  a wonderful case.

### Is this something you're interested in working on?

- [ ✔️ ] YES
- [ ] NO

**Comment by asmaerror06** [comment]
[ ✔️ ] YES

**Comment by asmaerror06** [comment]
[ ✔️ ] YES

**Comment by s3xysteak** [comment]
Close for inactive. And actually I am more interested in `unjs/nitro` now.
