### ISSUE TITLE
Sometimes, not enough language knowledge is given before going into action

### ISSUE THREAD

**Issue by microwavedd** [tuvtran/project-based-learning#554]
### Description

As said, I think that some of the languagues on the index are presented in a way too harsh-y manner.

I think some languages go right into the action without teaching the basics about the lenguage before. I know it's project based learning, but even there, I believe some of the projects are way too difficult for begginers or people who have no idea of how tha language works, and even though it could be a good learning technique for some, not for everyone.

Therefore, I suggest that, to make the project based learning repository more "compact" or "full" (as said meaning that you can learn the whole language without exiting the repo), I would add another link before the projects teaching the basics about the language or some video explaining how to use it. For instance, the lua/LOVE part does this, and it's pretty nice. (And not very difficult)

Just commenting based on my personal experience, other than that, this repo rocks. :))

**Comment by PrajwalBelur** [comment]
whats the issue
